services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles: ["dev"]
    restart: unless-stopped
    networks:
      - app_network

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    profiles: ["prod"]
    restart: unless-stopped
    networks:
      - app_network

#Networks:
networks:
  app_network:
    driver: bridge